### PR TITLE
Options page and optional tooltips.

### PR DESCRIPTION
**Pull request by sc0tt**
made buttons on the bar have the cursor mouse pointer.
added options page
added the ability to show tooltips on the bar. off by default, configurable in the options page.

### CODE REVIEW

**Comment by sc0tt** [comment]
per request of http://www.reddit.com/r/companion/comments/iqpup/18887_reddit_companion_users_heres_some_release/

reddit username: scottynosabe

**Comment by chromakode** [comment]
Thanks, Scott! 

Digging the sexy options page! If you don't mind, I'd love to break that off into a separate commit and merge it in.

I didn't know you could access the background page's localStorage when inside an extension iframe. That's a really neat trick.

IMHO tooltips are something that it would be better to have sane defaults for. If a button has no label text, I think it makes sense to have a tooltip. If the button already has a label (such as upvote/downvote), then a tooltip probably doesn't make sense. Do you think many users will want to disable the tooltips? What is your opinion on this?

Regarding the cursor change when hovering over buttons: no other buttons in the Chrome UI behave that way.

**Comment by sc0tt** [comment]
I don't mind at all!

Yeah, localStorage is an amazing feature. It's pretty awesome at the things you can do with them.

You are absolutely correct about the tooltips. Having them for things without label text is the most logical solution. 
As for the ability to disable them: Some users are going to want them disabled while others will keep them. In my experience dealing with optional features, as long as they aren't getting in the way, aren't taking up too many resources, and the user is able to disable the feature without confusion, then there isn't much of a reason not to have them

Cursor change: I didn't even think of that. Good catch!

**Comment by chromakode** [comment]
Scott,

I've merged in your options page and tooltips+toggle. I made some stylistic changes and split up your commits differently, but maintained your authorship since my changes are merely a derivative of your work. :)

Thanks very much for your patches. Use your new sorcerer powers wisely.

**Pull request closed without merging**
