### PR TITLE
Update background.js

### PR DESCRIPTION
**Pull request by dbovinett**
Changes to file in order to bring notifications up to rich text and away from the depreciated methods.  Changed formatting to be more consistent.  Modified notification to be capable of displaying more than just mail.  Added some functionality to the notification object in order to accommodate future use.  Used existing class style to extend functionality.  This does not address any other issue than the notifications, though the entire file has been tweaked because of the formatting.

### CODE REVIEW

**Comment by chromakode** [comment]
Thanks for the pull request!

Please separate style changes and individual functional changes into different commits with commit messages explaining each change before submitting a patchset for review. It is prohibitively time consuming to review and maintain a smushed-together diff with lots of different changes.

**Comment by dbovinett** [comment]
Understood.  I will do so and resubmit.

**Comment by chromakode** [comment]
Thanks!

**Comment by dbovinett** [comment]
I have submitted the formatting changes as a separate request and will submit a pull request for the changes I've made to address the API issues once that has been accepted/rejected.

**Pull request closed without merging**
