### PR TITLE
Added https support (disabled by default)

### PR DESCRIPTION
**Pull request by mhweaver**
I added 'https://*/*' to the matches for pageOverlay.js in the manifest, so this change would end up expanding the permissions of the companion a little bit.

Related to [issue #12](https://github.com/reddit/reddit-companion/issues/12) (probably shouldn't be closed yet)

### CODE REVIEW

**Comment by chromakode** [comment]
Code looks good! Can you please make a post in /r/community to see what the community thinks?

A nice touch would be to scan all tabs upon preference change and update the alien icon. Otherwise, after a preference changes, https pages will require a refresh before the alien icon shows up/hides. I'm going to be adding a preference change watch in background.js today (I hope), so maybe we can add that afterward.

**Comment by mhweaver** [comment]
[Posted](http://www.reddit.com/r/companion/comments/itzwm/secure_webpage_support_what_do_you_guys_think/).

Good call on doing all the tabs. I'll see what I can do when I get a chance.

**Comment by chromakode** [comment]
Awesome, thanks! Upvoted.

**Comment by mhweaver** [comment]
Well, at least I can say that I'm probably the only person with a 5+ year old account where 100% of their submission upvotes came from admins :D

**Comment by chromakode** [comment]
Merged in e8c6b029f8. Thanks!

**Pull request closed without merging**
